# global variable to use
COLLECTION = 'ISPY2'
SCAN = 'ISPY2: VOLSER: bi-lateral: SER'
MASK = 'ISPY2: VOLSER: bi-lateral: Analysis Mask'
PATIENT_IDS = ['ISPY2-105286']
TIMES = [0,1,2,3]

# target OUTPUT files for the whole workflow
rule all:
    input:
        expand("../workflow/results/scans/{patient_id}_{times}.nrrd", patient_id=PATIENT_IDS, times=TIMES)

rule download_images:
    params:
        collection = COLLECTION,
        scan = SCAN,
        mask = MASK,
        patient_ids = PATIENT_IDS,
        scan_storage = "../workflow/results/scans/",
        mask_storage = "../workflow/results/masks/"
    output:
        temporary(directory(expand("../workflow/results/scans/{patient_id}_{times}", patient_id=PATIENT_IDS, times=TIMES))),
        temporary(directory(expand("../workflow/results/masks/{patient_id}_{times}", patient_id=PATIENT_IDS, times=TIMES)))
    script:
        "../workflow/scripts/download_images.py"

rule process_scans:
    input:
        expand("../workflow/results/scans/{patient_id}_{times}", patient_id=PATIENT_IDS, times=TIMES),
    output:
        expand("../workflow/results/scans/{patient_id}_{times}.nrrd", patient_id=PATIENT_IDS, times=TIMES)
    script:
        "../workflow/scripts/process_scans.py"



