# target OUTPUT files for the whole workflow
rule all:
    input:
        "../workflow/results/scans/"

# global variable to use
COLLECTION = 'ISPY2'
SCAN = 'ISPY2: VOLSER: bi-lateral: SER'
MASK = 'ISPY2: VOLSER: bi-lateral: Analysis Mask'
PATIENT_ID = 'ISPY2-105286'
UPPERBOUND = 118
LOWERBOUND = 0

rule download_images:
    params:
        collection = COLLECTION,
        scan = SCAN,
        mask = MASK,
        patient_id = PATIENT_ID,
        scan_storage = "../workflow/results/scans/",
        mask_storage = "../workflow/results/masks/"
    conda:
        '/mnt/home/fesslerl/890-402/cmse_890_602_fessler_final/workflow/env/tcia_utils.yml'
    script:
        "../workflow/scripts/download_images.py"

rule process_masks:
    params:
        mask_long_storage = "../workflow/results/masks_long/"
    input:
        "{dataset}/inputfile"
    output:
        
    script:
        "../workflow/scripts/download_images.py"

